namespace ExpenseTrackerApi.Endpoints.Expenses;

/// <summary>
/// Response model for the ProcessExpense endpoint, containing details of the processed expense.
/// </summary>
public class ProcessExpenseResponse
{
    /// <summary>
    /// Unique identifier for the processed expense, generated by the database upon saving.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// The amount of the expense as determined by the AI. This value is required and must be greater than zero.
    /// </summary>
    public decimal Amount { get; set; }
    
    /// <summary>
    /// A brief description of the expense, generated by the AI.
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// The category to which the expense belongs, as determined by the AI.
    /// </summary>
    public string CategoryName { get; set; } = string.Empty;
}